# Generated by Django 5.1.2 on 2024-11-06 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_typeofbuilding_building_type_of_building'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='type_of_building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.typeofbuilding', verbose_name='Тип недвижимости'),
        ),
    ]
