# Generated by Django 5.1.2 on 2024-11-05 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Buyer', 'Buyer'), ('owner', 'Owner')], default='Buyer', max_length=10),
        ),
    ]
